# version: '3'
services:
  backend:
    build:
      context: ./backend
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env  # Specify the path to the .env file
    command: ["node", "server.js"]


