# version: '3'

services:
  backend:
    build:
      context: ./backend
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env  # Specify the path to the .env file
    command: ["node", "server.js"]

  plaid:
    build:
      context: ./Plaid
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env 
    command: ["node", "server.js"]
