# version: '3'
services:
  web_server:
    build:
      context: ./backend
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env  # Specify the path to the .env file
    command: ["node", "server.js"]
  
  plaid_api:
    build:
      context: ./plaid
    depends_on:
      - web_server
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - ./plaid/.env
    command: ["node","server.js"]



